name: chat_bubbles
description: Flutter chat bubble widgets, similar to Whatsapp and more shapes. Easy to use and implement
  chat bubbles.
version: 1.6.0
homepage: https://github.com/prahack/chat_bubbles

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  intl: "0.18.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Flutter chat_bubbles package logo.
    path: images/logo/logo.png

flutter:

